name: Test
on: [push, pull_request]
jobs:
  test-format:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Format
      run: diff -u <(echo -n) <(gofmt -s -d .)
    - name: Test
      run: go test ./...
